import cowsay
print()
print()
print()
print()
print()
cowsay.trex('Holeni Wa Maxangu Hi Mina!!')
print()
print()
print("                                                            Nsovo W. Maswanganyi")
print()
print()
print()
print()
